### ISSUE TITLE
Make 0.1 release with the Kits Ready-to-use

### ISSUE THREAD

**Issue by frostyandy2k** [ScaleIT-Org/workshop-app-prototyping#3]
I should just need to download a released version and print it.

**Comment by laurahalbmann** [comment]
Powerpoint ist in Ordnung. 

Bilder würde ich noch austauschen - z.B. Origami?

**Comment by frostyandy2k** [comment]
Wenn du neue bilder hast, dann ja, ansonsten ist der Aufwand vielleicht viel zu groß. Vorschläge?

**Comment by laurahalbmann** [comment]
Neue Bilder leider nicht. Daher so wie es ist Ok.
