### ISSUE TITLE
Add links to origami making in readme

### ISSUE THREAD

**Issue by frostyandy2k** [ScaleIT-Org/workshop-app-prototyping#9]

**Comment by laurahalbmann** [comment]
Hi Andrei, 

die Links sind eingefügt. Kann man das vielleicht noch Aufhübschen und einen Hyperlink setzen?

**Comment by frostyandy2k** [comment]
Man kann alles ;) 

Syntax für links:

`![Origami Box](https://www.origami-kunst.de/faltanleitungen/diagramme/multibox/)`

Resultat:
![Origami Box](https://www.origami-kunst.de/faltanleitungen/diagramme/multibox/)

**Comment by frostyandy2k** [comment]
My bad.

Link Syntax without !
     
       [Origami Box](https://www.origami-kunst.de/faltanleitungen/diagramme/multibox/)

Resultat:
[Origami Box](https://www.origami-kunst.de/faltanleitungen/diagramme/multibox/)

**Comment by frostyandy2k** [comment]
Changed readme accordingly
